const goodsData = {
  products: [
    {
      id: 1,
      title: 'Essence Mascara Lash Princess',
      description:
        'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
      price: 9.99,
      discountPercentage: 7.17,
      rating: 4.94,
      stock: 5,
      brand: 'Essence',
      category: 'beauty',
      thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png'],
    },
    {
      id: 2,
      title: 'Eyeshadow Palette with Mirror',
      description:
        "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
      price: 19.99,
      discountPercentage: 5.5,
      rating: 3.28,
      stock: 44,
      brand: 'Glamour Beauty',
      category: 'beauty',
      thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png'],
    },
    {
      id: 3,
      title: 'Powder Canister',
      description:
        'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
      price: 14.99,
      discountPercentage: 18.14,
      rating: 3.82,
      stock: 59,
      brand: 'Velvet Touch',
      category: 'beauty',
      thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png'],
    },
    {
      id: 4,
      title: 'Red Lipstick',
      description:
        'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
      price: 12.99,
      discountPercentage: 19.03,
      rating: 2.51,
      stock: 68,
      brand: 'Chic Cosmetics',
      category: 'beauty',
      thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png'],
    },
    {
      id: 5,
      title: 'Red Nail Polish',
      description:
        'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
      price: 8.99,
      discountPercentage: 2.46,
      rating: 3.91,
      stock: 71,
      brand: 'Nail Couture',
      category: 'beauty',
      thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png'],
    },
    {
      id: 6,
      title: 'Calvin Klein CK One',
      description:
        "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
      price: 49.99,
      discountPercentage: 0.32,
      rating: 4.85,
      stock: 17,
      brand: 'Calvin Klein',
      category: 'fragrances',
      thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/2.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/3.png',
      ],
    },
    {
      id: 7,
      title: 'Chanel Coco Noir Eau De',
      description:
        'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
      price: 129.99,
      discountPercentage: 18.64,
      rating: 2.76,
      stock: 41,
      brand: 'Chanel',
      category: 'fragrances',
      thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/1.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/2.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/3.png',
      ],
    },
    {
      id: 8,
      title: "Dior J'adore",
      description:
        "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
      price: 89.99,
      discountPercentage: 17.44,
      rating: 3.31,
      stock: 91,
      brand: 'Dior',
      category: 'fragrances',
      thumbnail: "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/thumbnail.png",
      images: [
        "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/1.png",
        "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/2.png",
        "https://cdn.dummyjson.com/products/images/fragrances/Dior%20J'adore/3.png",
      ],
    },
    {
      id: 9,
      title: 'Dolce Shine Eau de',
      description:
        "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
      price: 69.99,
      discountPercentage: 11.47,
      rating: 2.68,
      stock: 3,
      brand: 'Dolce & Gabbana',
      category: 'fragrances',
      thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/1.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/2.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Dolce%20Shine%20Eau%20de/3.png',
      ],
    },
    {
      id: 10,
      title: 'Gucci Bloom Eau de',
      description:
        "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
      price: 79.99,
      discountPercentage: 8.9,
      rating: 2.69,
      stock: 93,
      brand: 'Gucci',
      category: 'fragrances',
      thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/1.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/2.png',
        'https://cdn.dummyjson.com/products/images/fragrances/Gucci%20Bloom%20Eau%20de/3.png',
      ],
    },
    {
      id: 11,
      title: 'Annibale Colombo Bed',
      description:
        'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
      price: 1899.99,
      discountPercentage: 0.29,
      rating: 4.14,
      stock: 47,
      brand: 'Annibale Colombo',
      category: 'furniture',
      thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png',
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png',
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png',
      ],
    },
    {
      id: 12,
      title: 'Annibale Colombo Sofa',
      description:
        'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
      price: 2499.99,
      discountPercentage: 18.54,
      rating: 3.08,
      stock: 16,
      brand: 'Annibale Colombo',
      category: 'furniture',
      thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png',
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png',
        'https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png',
      ],
    },
    {
      id: 13,
      title: 'Bedside Table African Cherry',
      description:
        'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.',
      price: 299.99,
      discountPercentage: 9.58,
      rating: 4.48,
      stock: 16,
      brand: 'Furniture Co.',
      category: 'furniture',
      thumbnail: 'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/1.png',
        'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/2.png',
        'https://cdn.dummyjson.com/products/images/furniture/Bedside%20Table%20African%20Cherry/3.png',
      ],
    },
    {
      id: 14,
      title: 'Knoll Saarinen Executive Conference Chair',
      description:
        'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.',
      price: 499.99,
      discountPercentage: 15.23,
      rating: 4.11,
      stock: 47,
      brand: 'Knoll',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/1.png',
        'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/2.png',
        'https://cdn.dummyjson.com/products/images/furniture/Knoll%20Saarinen%20Executive%20Conference%20Chair/3.png',
      ],
    },
    {
      id: 15,
      title: 'Wooden Bathroom Sink With Mirror',
      description:
        'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.',
      price: 799.99,
      discountPercentage: 11.22,
      rating: 3.26,
      stock: 95,
      brand: 'Bath Trends',
      category: 'furniture',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/1.png',
        'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/2.png',
        'https://cdn.dummyjson.com/products/images/furniture/Wooden%20Bathroom%20Sink%20With%20Mirror/3.png',
      ],
    },
    {
      id: 16,
      title: 'Apple MacBook Pro 14 Inch Space Grey',
      description:
        "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
      price: 1999.99,
      discountPercentage: 9.25,
      rating: 3.13,
      stock: 39,
      brand: 'Apple',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/1.png',
        'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/2.png',
        'https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/3.png',
      ],
    },
    {
      id: 17,
      title: 'Asus Zenbook Pro Dual Screen Laptop',
      description:
        'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.',
      price: 1799.99,
      discountPercentage: 9.21,
      rating: 3.14,
      stock: 38,
      brand: 'Asus',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/1.png',
        'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/2.png',
        'https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/3.png',
      ],
    },
    {
      id: 18,
      title: 'Huawei Matebook X Pro',
      description:
        'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.',
      price: 1399.99,
      discountPercentage: 15.25,
      rating: 4.62,
      stock: 34,
      brand: 'Huawei',
      category: 'laptops',
      thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/1.png',
        'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/2.png',
        'https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/3.png',
      ],
    },
    {
      id: 19,
      title: 'Lenovo Yoga 920',
      description:
        'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.',
      price: 1099.99,
      discountPercentage: 7.77,
      rating: 2.98,
      stock: 71,
      brand: 'Lenovo',
      category: 'laptops',
      thumbnail: 'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/1.png',
        'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/2.png',
        'https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/3.png',
      ],
    },
    {
      id: 20,
      title: 'New DELL XPS 13 9300 Laptop',
      description:
        'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.',
      price: 1499.99,
      discountPercentage: 11.7,
      rating: 2.98,
      stock: 18,
      brand: 'Dell',
      category: 'laptops',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/1.png',
        'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/2.png',
        'https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/3.png',
      ],
    },
    {
      id: 21,
      title: 'Blue & Black Check Shirt',
      description:
        "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
      price: 29.99,
      discountPercentage: 1.41,
      rating: 4.19,
      stock: 44,
      brand: 'Fashion Trends',
      category: 'mens-shirts',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/4.png',
      ],
    },
    {
      id: 22,
      title: 'Gigabyte Aorus Men Tshirt',
      description:
        "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      price: 24.99,
      discountPercentage: 12.6,
      rating: 4.95,
      stock: 64,
      brand: 'Gigabyte',
      category: 'mens-shirts',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/4.png',
      ],
    },
    {
      id: 23,
      title: 'Man Plaid Shirt',
      description:
        "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
      price: 34.99,
      discountPercentage: 17.53,
      rating: 3.66,
      stock: 65,
      brand: 'Classic Wear',
      category: 'mens-shirts',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Plaid%20Shirt/4.png',
      ],
    },
    {
      id: 24,
      title: 'Man Short Sleeve Shirt',
      description:
        "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
      price: 19.99,
      discountPercentage: 8.65,
      rating: 4.62,
      stock: 20,
      brand: 'Casual Comfort',
      category: 'mens-shirts',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Man%20Short%20Sleeve%20Shirt/4.png',
      ],
    },
    {
      id: 25,
      title: 'Men Check Shirt',
      description:
        'The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.',
      price: 27.99,
      discountPercentage: 14.21,
      rating: 2.9,
      stock: 69,
      brand: 'Urban Chic',
      category: 'mens-shirts',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shirts/Men%20Check%20Shirt/4.png',
      ],
    },
    {
      id: 26,
      title: 'Nike Air Jordan 1 Red And Black',
      description:
        'The Nike Air Jordan 1 in Red and Black is an iconic basketball sneaker known for its stylish design and high-performance features, making it a favorite among sneaker enthusiasts and athletes.',
      price: 149.99,
      discountPercentage: 15.82,
      rating: 2.77,
      stock: 15,
      brand: 'Nike',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Air%20Jordan%201%20Red%20And%20Black/4.png',
      ],
    },
    {
      id: 27,
      title: 'Nike Baseball Cleats',
      description:
        'Nike Baseball Cleats are designed for maximum traction and performance on the baseball field. They provide stability and support for players during games and practices.',
      price: 79.99,
      discountPercentage: 11.4,
      rating: 4.01,
      stock: 14,
      brand: 'Nike',
      category: 'mens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Nike%20Baseball%20Cleats/4.png',
      ],
    },
    {
      id: 28,
      title: 'Puma Future Rider Trainers',
      description:
        'The Puma Future Rider Trainers offer a blend of retro style and modern comfort. Perfect for casual wear, these trainers provide a fashionable and comfortable option for everyday use.',
      price: 89.99,
      discountPercentage: 3.64,
      rating: 4.85,
      stock: 10,
      brand: 'Puma',
      category: 'mens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Puma%20Future%20Rider%20Trainers/4.png',
      ],
    },
    {
      id: 29,
      title: 'Sports Sneakers Off White & Red',
      description:
        'The Sports Sneakers in Off White and Red combine style and functionality, making them a fashionable choice for sports enthusiasts. The red and off-white color combination adds a bold and energetic touch.',
      price: 119.99,
      discountPercentage: 11.69,
      rating: 4.92,
      stock: 73,
      brand: 'Off White',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/4.png',
      ],
    },
    {
      id: 30,
      title: 'Sports Sneakers Off White Red',
      description:
        'Another variant of the Sports Sneakers in Off White Red, featuring a unique design. These sneakers offer style and comfort for casual occasions.',
      price: 109.99,
      discountPercentage: 17.22,
      rating: 2.95,
      stock: 75,
      brand: 'Off White',
      category: 'mens-shoes',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/1.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/2.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/3.png',
        'https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20Red/4.png',
      ],
    },
    {
      id: 31,
      title: 'Brown Leather Belt Watch',
      description:
        'The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.',
      price: 89.99,
      discountPercentage: 15.01,
      rating: 4.47,
      stock: 69,
      brand: 'Fashion Timepieces',
      category: 'mens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/3.png',
      ],
    },
    {
      id: 32,
      title: 'Longines Master Collection',
      description:
        "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
      price: 1499.99,
      discountPercentage: 0.64,
      rating: 2.64,
      stock: 65,
      brand: 'Longines',
      category: 'mens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/3.png',
      ],
    },
    {
      id: 33,
      title: 'Rolex Cellini Date Black Dial',
      description:
        "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
      price: 8999.99,
      discountPercentage: 14.28,
      rating: 3.61,
      stock: 84,
      brand: 'Rolex',
      category: 'mens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/3.png',
      ],
    },
    {
      id: 34,
      title: 'Rolex Cellini Moonphase',
      description:
        "The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex's commitment to precision and elegance.",
      price: 12999.99,
      discountPercentage: 5.7,
      rating: 4.52,
      stock: 33,
      brand: 'Rolex',
      category: 'mens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Moonphase/3.png',
      ],
    },
    {
      id: 35,
      title: 'Rolex Datejust',
      description:
        "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
      price: 10999.99,
      discountPercentage: 9.69,
      rating: 4.94,
      stock: 11,
      brand: 'Rolex',
      category: 'mens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/3.png',
      ],
    },
    {
      id: 36,
      title: 'Rolex Submariner Watch',
      description:
        "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
      price: 13999.99,
      discountPercentage: 0.82,
      rating: 2.97,
      stock: 35,
      brand: 'Rolex',
      category: 'mens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/1.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/2.png',
        'https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/3.png',
      ],
    },
    {
      id: 37,
      title: 'Amazon Echo Plus',
      description:
        'The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.',
      price: 99.99,
      discountPercentage: 16.3,
      rating: 3.52,
      stock: 50,
      brand: 'Amazon',
      category: 'mobile-accessories',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/2.png',
      ],
    },
    {
      id: 38,
      title: 'Apple Airpods',
      description:
        'The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.',
      price: 129.99,
      discountPercentage: 4.82,
      rating: 4.38,
      stock: 93,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/2.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpods/3.png',
      ],
    },
    {
      id: 39,
      title: 'Apple AirPods Max Silver',
      description:
        'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.',
      price: 549.99,
      discountPercentage: 11.7,
      rating: 3.11,
      stock: 7,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/1.png'],
    },
    {
      id: 40,
      title: 'Apple Airpower Wireless Charger',
      description:
        'The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.',
      price: 79.99,
      discountPercentage: 6.54,
      rating: 4.51,
      stock: 78,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpower%20Wireless%20Charger/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Airpower%20Wireless%20Charger/1.png',
      ],
    },
    {
      id: 41,
      title: 'Apple HomePod Mini Cosmic Grey',
      description:
        'The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience.',
      price: 99.99,
      discountPercentage: 3.7,
      rating: 4.51,
      stock: 65,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20HomePod%20Mini%20Cosmic%20Grey/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20HomePod%20Mini%20Cosmic%20Grey/1.png',
      ],
    },
    {
      id: 42,
      title: 'Apple iPhone Charger',
      description:
        'The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.',
      price: 19.99,
      discountPercentage: 1.01,
      rating: 3.03,
      stock: 4,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20iPhone%20Charger/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20iPhone%20Charger/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20iPhone%20Charger/2.png',
      ],
    },
    {
      id: 43,
      title: 'Apple MagSafe Battery Pack',
      description:
        'The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.',
      price: 99.99,
      discountPercentage: 10.27,
      rating: 2.61,
      stock: 80,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20MagSafe%20Battery%20Pack/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20MagSafe%20Battery%20Pack/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20MagSafe%20Battery%20Pack/2.png',
      ],
    },
    {
      id: 44,
      title: 'Apple Watch Series 4 Gold',
      description:
        'The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.',
      price: 349.99,
      discountPercentage: 5.14,
      rating: 4.42,
      stock: 68,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/2.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/3.png',
      ],
    },
    {
      id: 45,
      title: 'Beats Flex Wireless Earphones',
      description:
        'The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.',
      price: 49.99,
      discountPercentage: 8.27,
      rating: 4.17,
      stock: 49,
      brand: 'Beats',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Beats%20Flex%20Wireless%20Earphones/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Beats%20Flex%20Wireless%20Earphones/1.png',
      ],
    },
    {
      id: 46,
      title: 'iPhone 12 Silicone Case with MagSafe Plum',
      description:
        'The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.',
      price: 29.99,
      discountPercentage: 14.35,
      rating: 4.41,
      stock: 51,
      brand: 'Apple',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/2.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/3.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/4.png',
      ],
    },
    {
      id: 47,
      title: 'Monopod',
      description:
        'The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease.',
      price: 19.99,
      discountPercentage: 11.62,
      rating: 2.99,
      stock: 96,
      brand: 'TechGear',
      category: 'mobile-accessories',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/1.png',
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/2.png',
      ],
    },
    {
      id: 48,
      title: 'Selfie Lamp with iPhone',
      description:
        'The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos.',
      price: 14.99,
      discountPercentage: 13.86,
      rating: 2.84,
      stock: 89,
      brand: 'GadgetMaster',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Lamp%20with%20iPhone/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Lamp%20with%20iPhone/1.png'],
    },
    {
      id: 49,
      title: 'Selfie Stick Monopod',
      description:
        'The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras.',
      price: 12.99,
      discountPercentage: 15.29,
      rating: 2.93,
      stock: 33,
      brand: 'SnapTech',
      category: 'mobile-accessories',
      thumbnail: 'https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/1.png'],
    },
    {
      id: 50,
      title: 'TV Studio Camera Pedestal',
      description:
        'The TV Studio Camera Pedestal is a professional-grade camera support system for smooth and precise camera movements in a studio setting. Ideal for broadcast and production.',
      price: 499.99,
      discountPercentage: 10.28,
      rating: 4.05,
      stock: 45,
      brand: 'ProVision',
      category: 'mobile-accessories',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/thumbnail.png',
      images: ['https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/1.png'],
    },
    {
      id: 51,
      title: 'Generic Motorcycle',
      description:
        'The Generic Motorcycle is a versatile and reliable bike suitable for various riding preferences. With a balanced design, it provides a comfortable and efficient riding experience.',
      price: 3999.99,
      discountPercentage: 2.89,
      rating: 4.85,
      stock: 63,
      brand: 'Generic Motors',
      category: 'motorcycle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/1.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/2.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/3.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Generic%20Motorcycle/4.png',
      ],
    },
    {
      id: 52,
      title: 'Kawasaki Z800',
      description:
        "The Kawasaki Z800 is a powerful and agile sportbike known for its striking design and performance. It's equipped with advanced features, making it a favorite among motorcycle enthusiasts.",
      price: 8999.99,
      discountPercentage: 15.07,
      rating: 4.06,
      stock: 88,
      brand: 'Kawasaki',
      category: 'motorcycle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/1.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/2.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/3.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Kawasaki%20Z800/4.png',
      ],
    },
    {
      id: 53,
      title: 'MotoGP CI.H1',
      description:
        'The MotoGP CI.H1 is a high-performance motorcycle inspired by MotoGP racing technology. It offers cutting-edge features and precision engineering for an exhilarating riding experience.',
      price: 14999.99,
      discountPercentage: 17,
      rating: 4.15,
      stock: 85,
      brand: 'MotoGP',
      category: 'motorcycle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/1.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/2.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/3.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/MotoGP%20CI.H1/4.png',
      ],
    },
    {
      id: 54,
      title: 'Scooter Motorcycle',
      description:
        'The Scooter Motorcycle is a practical and fuel-efficient bike ideal for urban commuting. It features a step-through design and user-friendly controls for easy maneuverability.',
      price: 2999.99,
      discountPercentage: 19.19,
      rating: 3.33,
      stock: 11,
      brand: 'ScootMaster',
      category: 'motorcycle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/1.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/2.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/3.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Scooter%20Motorcycle/4.png',
      ],
    },
    {
      id: 55,
      title: 'Sportbike Motorcycle',
      description:
        "The Sportbike Motorcycle is designed for speed and agility, with a sleek and aerodynamic profile. It's suitable for riders looking for a dynamic and thrilling riding experience.",
      price: 7499.99,
      discountPercentage: 18.07,
      rating: 2.97,
      stock: 12,
      brand: 'SpeedMaster',
      category: 'motorcycle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/1.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/2.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/3.png',
        'https://cdn.dummyjson.com/products/images/motorcycle/Sportbike%20Motorcycle/4.png',
      ],
    },
    {
      id: 56,
      title: 'Attitude Super Leaves Hand Soap',
      description:
        'Attitude Super Leaves Hand Soap is a natural and nourishing hand soap enriched with the goodness of super leaves. It cleanses and moisturizes your hands, leaving them feeling fresh and soft.',
      price: 8.99,
      discountPercentage: 17.42,
      rating: 4.68,
      stock: 98,
      brand: 'Attitude',
      category: 'skin-care',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/1.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/2.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Attitude%20Super%20Leaves%20Hand%20Soap/3.png',
      ],
    },
    {
      id: 57,
      title: 'Olay Ultra Moisture Shea Butter Body Wash',
      description:
        'Olay Ultra Moisture Shea Butter Body Wash is a luxurious body wash that hydrates and nourishes your skin with the moisturizing power of shea butter. Enjoy a rich lather and silky-smooth skin.',
      price: 12.99,
      discountPercentage: 16.95,
      rating: 4.81,
      stock: 43,
      brand: 'Olay',
      category: 'skin-care',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/1.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/2.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Olay%20Ultra%20Moisture%20Shea%20Butter%20Body%20Wash/3.png',
      ],
    },
    {
      id: 58,
      title: 'Vaseline Men Body and Face Lotion',
      description:
        "Vaseline Men Body and Face Lotion is a specially formulated lotion designed to provide long-lasting moisture to men's skin. It absorbs quickly and helps keep the skin hydrated and healthy.",
      price: 9.99,
      discountPercentage: 11.63,
      rating: 3.97,
      stock: 54,
      brand: 'Vaseline',
      category: 'skin-care',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/1.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/2.png',
        'https://cdn.dummyjson.com/products/images/skin-care/Vaseline%20Men%20Body%20and%20Face%20Lotion/3.png',
      ],
    },
    {
      id: 59,
      title: 'iPhone 5s',
      description:
        "The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it's an older model, it still provides a reliable user experience.",
      price: 199.99,
      discountPercentage: 11.85,
      rating: 3.92,
      stock: 65,
      brand: 'Apple',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%205s/3.png',
      ],
    },
    {
      id: 60,
      title: 'iPhone 6',
      description:
        'The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.',
      price: 299.99,
      discountPercentage: 4.54,
      rating: 3.76,
      stock: 99,
      brand: 'Apple',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%206/3.png',
      ],
    },
    {
      id: 61,
      title: 'iPhone 13 Pro',
      description:
        'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.',
      price: 1099.99,
      discountPercentage: 18.3,
      rating: 3.42,
      stock: 26,
      brand: 'Apple',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/3.png',
      ],
    },
    {
      id: 62,
      title: 'iPhone X',
      description:
        'The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.',
      price: 899.99,
      discountPercentage: 14.19,
      rating: 4.96,
      stock: 99,
      brand: 'Apple',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/3.png',
      ],
    },
    {
      id: 63,
      title: 'Oppo A57',
      description:
        'The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.',
      price: 249.99,
      discountPercentage: 12.17,
      rating: 3.1,
      stock: 76,
      brand: 'Oppo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/3.png',
      ],
    },
    {
      id: 64,
      title: 'Oppo F19 Pro Plus',
      description:
        'The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.',
      price: 399.99,
      discountPercentage: 15.62,
      rating: 2.57,
      stock: 92,
      brand: 'Oppo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/3.png',
      ],
    },
    {
      id: 65,
      title: 'Oppo K1',
      description:
        'The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.',
      price: 299.99,
      discountPercentage: 14.58,
      rating: 3.39,
      stock: 61,
      brand: 'Oppo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/3.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/4.png',
      ],
    },
    {
      id: 66,
      title: 'Realme C35',
      description:
        'The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.',
      price: 149.99,
      discountPercentage: 16.47,
      rating: 2.56,
      stock: 81,
      brand: 'Realme',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/3.png',
      ],
    },
    {
      id: 67,
      title: 'Realme X',
      description:
        'The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.',
      price: 299.99,
      discountPercentage: 2.39,
      rating: 4.42,
      stock: 87,
      brand: 'Realme',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/3.png',
      ],
    },
    {
      id: 68,
      title: 'Realme XT',
      description:
        'The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.',
      price: 349.99,
      discountPercentage: 3.03,
      rating: 4.14,
      stock: 53,
      brand: 'Realme',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/3.png',
      ],
    },
    {
      id: 69,
      title: 'Samsung Galaxy S7',
      description:
        'The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.',
      price: 299.99,
      discountPercentage: 8.83,
      rating: 4.9,
      stock: 55,
      brand: 'Samsung',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/3.png',
      ],
    },
    {
      id: 70,
      title: 'Samsung Galaxy S8',
      description:
        'The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.',
      price: 499.99,
      discountPercentage: 2.69,
      rating: 3.69,
      stock: 75,
      brand: 'Samsung',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/3.png',
      ],
    },
    {
      id: 71,
      title: 'Samsung Galaxy S10',
      description:
        'The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.',
      price: 699.99,
      discountPercentage: 0.97,
      rating: 2.81,
      stock: 40,
      brand: 'Samsung',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/3.png',
      ],
    },
    {
      id: 72,
      title: 'Vivo S1',
      description:
        'The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.',
      price: 249.99,
      discountPercentage: 4.25,
      rating: 2.83,
      stock: 13,
      brand: 'Vivo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/3.png',
      ],
    },
    {
      id: 73,
      title: 'Vivo V9',
      description:
        'The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.',
      price: 299.99,
      discountPercentage: 14.57,
      rating: 3.1,
      stock: 19,
      brand: 'Vivo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/3.png',
      ],
    },
    {
      id: 74,
      title: 'Vivo X21',
      description:
        'The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.',
      price: 499.99,
      discountPercentage: 7.32,
      rating: 2.75,
      stock: 0,
      brand: 'Vivo',
      category: 'smartphones',
      thumbnail: 'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/1.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/2.png',
        'https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/3.png',
      ],
    },
    {
      id: 75,
      title: 'Black Sun Glasses',
      description:
        'The Black Sun Glasses are a classic and stylish choice, featuring a sleek black frame and tinted lenses. They provide both UV protection and a fashionable look.',
      price: 29.99,
      discountPercentage: 14.22,
      rating: 3.23,
      stock: 100,
      brand: 'Fashion Shades',
      category: 'sunglasses',
      thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Black%20Sun%20Glasses/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/sunglasses/Black%20Sun%20Glasses/1.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Black%20Sun%20Glasses/2.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Black%20Sun%20Glasses/3.png',
      ],
    },
    {
      id: 76,
      title: 'Classic Sun Glasses',
      description:
        'The Classic Sun Glasses offer a timeless design with a neutral frame and UV-protected lenses. These sunglasses are versatile and suitable for various occasions.',
      price: 24.99,
      discountPercentage: 15.67,
      rating: 2.99,
      stock: 100,
      brand: 'Fashion Shades',
      category: 'sunglasses',
      thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Classic%20Sun%20Glasses/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/sunglasses/Classic%20Sun%20Glasses/1.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Classic%20Sun%20Glasses/2.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Classic%20Sun%20Glasses/3.png',
      ],
    },
    {
      id: 77,
      title: 'Green and Black Glasses',
      description:
        'The Green and Black Glasses feature a bold combination of green and black colors, adding a touch of vibrancy to your eyewear collection. They are both stylish and eye-catching.',
      price: 34.99,
      discountPercentage: 10.75,
      rating: 2.84,
      stock: 74,
      brand: 'Fashion Shades',
      category: 'sunglasses',
      thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Green%20and%20Black%20Glasses/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/sunglasses/Green%20and%20Black%20Glasses/1.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Green%20and%20Black%20Glasses/2.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Green%20and%20Black%20Glasses/3.png',
      ],
    },
    {
      id: 78,
      title: 'Party Glasses',
      description:
        "The Party Glasses are designed to add flair to your party outfit. With unique shapes or colorful frames, they're perfect for adding a playful touch to your look during celebrations.",
      price: 19.99,
      discountPercentage: 19.52,
      rating: 3.21,
      stock: 35,
      brand: 'Fashion Fun',
      category: 'sunglasses',
      thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Party%20Glasses/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/sunglasses/Party%20Glasses/1.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Party%20Glasses/2.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Party%20Glasses/3.png',
      ],
    },
    {
      id: 79,
      title: 'Sunglasses',
      description:
        'The Sunglasses offer a classic and simple design with a focus on functionality. These sunglasses provide essential UV protection while maintaining a timeless look.',
      price: 22.99,
      discountPercentage: 4.87,
      rating: 2.58,
      stock: 59,
      brand: 'Fashion Shades',
      category: 'sunglasses',
      thumbnail: 'https://cdn.dummyjson.com/products/images/sunglasses/Sunglasses/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/sunglasses/Sunglasses/1.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Sunglasses/2.png',
        'https://cdn.dummyjson.com/products/images/sunglasses/Sunglasses/3.png',
      ],
    },
    {
      id: 80,
      title: 'iPad Mini 2021 Starlight',
      description:
        'The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.',
      price: 499.99,
      discountPercentage: 19.48,
      rating: 3.87,
      stock: 32,
      brand: 'Apple',
      category: 'tablets',
      thumbnail: 'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/1.png',
        'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/2.png',
        'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/3.png',
        'https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/4.png',
      ],
    },
    {
      id: 81,
      title: 'Samsung Galaxy Tab S8 Plus Grey',
      description:
        "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment.",
      price: 599.99,
      discountPercentage: 8.11,
      rating: 3.43,
      stock: 76,
      brand: 'Samsung',
      category: 'tablets',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/1.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/2.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/3.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/4.png',
      ],
    },
    {
      id: 82,
      title: 'Samsung Galaxy Tab White',
      description:
        'The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.',
      price: 349.99,
      discountPercentage: 4.82,
      rating: 3.7,
      stock: 0,
      brand: 'Samsung',
      category: 'tablets',
      thumbnail: 'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/1.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/2.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/3.png',
        'https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20White/4.png',
      ],
    },
    {
      id: 83,
      title: '300 Touring',
      description:
        'The 300 Touring is a stylish and comfortable sedan, known for its luxurious features and smooth performance.',
      price: 28999.99,
      discountPercentage: 7.15,
      rating: 4.56,
      stock: 53,
      brand: 'Chrysler',
      category: 'vehicle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/1.png',
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/2.png',
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/3.png',
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/4.png',
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/5.png',
        'https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/6.png',
      ],
    },
    {
      id: 84,
      title: 'Charger SXT RWD',
      description:
        'The Charger SXT RWD is a powerful and sporty rear-wheel-drive sedan, offering a blend of performance and practicality.',
      price: 32999.99,
      discountPercentage: 2.27,
      rating: 2.92,
      stock: 85,
      brand: 'Dodge',
      category: 'vehicle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/1.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/2.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/3.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/4.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/5.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Charger%20SXT%20RWD/6.png',
      ],
    },
    {
      id: 85,
      title: 'Dodge Hornet GT Plus',
      description:
        'The Dodge Hornet GT Plus is a compact and agile hatchback, perfect for urban driving with a touch of sportiness.',
      price: 24999.99,
      discountPercentage: 14.26,
      rating: 3.93,
      stock: 81,
      brand: 'Dodge',
      category: 'vehicle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/1.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/2.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/3.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/4.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/5.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Dodge%20Hornet%20GT%20Plus/6.png',
      ],
    },
    {
      id: 86,
      title: 'Durango SXT RWD',
      description:
        'The Durango SXT RWD is a spacious and versatile SUV, known for its strong performance and family-friendly features.',
      price: 36999.99,
      discountPercentage: 9.21,
      rating: 3.47,
      stock: 0,
      brand: 'Dodge',
      category: 'vehicle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/1.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/2.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/3.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/4.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/5.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Durango%20SXT%20RWD/6.png',
      ],
    },
    {
      id: 87,
      title: 'Pacifica Touring',
      description:
        'The Pacifica Touring is a stylish and well-equipped minivan, offering comfort and convenience for family journeys.',
      price: 31999.99,
      discountPercentage: 6.89,
      rating: 2.96,
      stock: 22,
      brand: 'Chrysler',
      category: 'vehicle',
      thumbnail: 'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/1.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/2.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/3.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/4.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/5.png',
        'https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/6.png',
      ],
    },
    {
      id: 88,
      title: "Blue Women's Handbag",
      description:
        "The Blue Women's Handbag is a stylish and spacious accessory for everyday use. With a vibrant blue color and multiple compartments, it combines fashion and functionality.",
      price: 49.99,
      discountPercentage: 5.24,
      rating: 3.37,
      stock: 76,
      brand: 'Fashionista',
      category: 'womens-bags',
      thumbnail: "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/thumbnail.png",
      images: [
        "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/1.png",
        "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/2.png",
        "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/3.png",
      ],
    },
    {
      id: 89,
      title: "Heshe Women's Leather Bag",
      description:
        "The Heshe Women's Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman. With a timeless design and durable craftsmanship, it's a versatile accessory.",
      price: 129.99,
      discountPercentage: 7.74,
      rating: 2.62,
      stock: 9,
      brand: 'Heshe',
      category: 'womens-bags',
      thumbnail: "https://cdn.dummyjson.com/products/images/womens-bags/Heshe%20Women's%20Leather%20Bag/thumbnail.png",
      images: [
        "https://cdn.dummyjson.com/products/images/womens-bags/Heshe%20Women's%20Leather%20Bag/1.png",
        "https://cdn.dummyjson.com/products/images/womens-bags/Heshe%20Women's%20Leather%20Bag/2.png",
        "https://cdn.dummyjson.com/products/images/womens-bags/Heshe%20Women's%20Leather%20Bag/3.png",
      ],
    },
    {
      id: 90,
      title: 'Prada Women Bag',
      description:
        "The Prada Women Bag is an iconic designer bag that exudes elegance and luxury. Crafted with precision and featuring the Prada logo, it's a statement piece for fashion enthusiasts.",
      price: 599.99,
      discountPercentage: 18.3,
      rating: 3.52,
      stock: 43,
      brand: 'Prada',
      category: 'womens-bags',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-bags/Prada%20Women%20Bag/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-bags/Prada%20Women%20Bag/1.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/Prada%20Women%20Bag/2.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/Prada%20Women%20Bag/3.png',
      ],
    },
    {
      id: 91,
      title: 'White Faux Leather Backpack',
      description:
        "The White Faux Leather Backpack is a trendy and practical backpack for the modern woman. With a sleek white design and ample storage space, it's perfect for both casual and on-the-go styles.",
      price: 39.99,
      discountPercentage: 7.76,
      rating: 4.91,
      stock: 89,
      brand: 'Urban Chic',
      category: 'womens-bags',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/womens-bags/White%20Faux%20Leather%20Backpack/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-bags/White%20Faux%20Leather%20Backpack/1.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/White%20Faux%20Leather%20Backpack/2.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/White%20Faux%20Leather%20Backpack/3.png',
      ],
    },
    {
      id: 92,
      title: 'Women Handbag Black',
      description:
        "The Women Handbag in Black is a classic and versatile accessory that complements various outfits. With a timeless black color and functional design, it's a must-have in every woman's wardrobe.",
      price: 59.99,
      discountPercentage: 3.08,
      rating: 4.94,
      stock: 24,
      brand: 'Elegance Collection',
      category: 'womens-bags',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-bags/Women%20Handbag%20Black/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-bags/Women%20Handbag%20Black/1.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/Women%20Handbag%20Black/2.png',
        'https://cdn.dummyjson.com/products/images/womens-bags/Women%20Handbag%20Black/3.png',
      ],
    },
    {
      id: 93,
      title: 'Black & Brown Slipper',
      description:
        'The Black & Brown Slipper is a comfortable and stylish choice for casual wear. Featuring a blend of black and brown colors, it adds a touch of sophistication to your relaxation.',
      price: 19.99,
      discountPercentage: 13.62,
      rating: 4.13,
      stock: 80,
      brand: 'Comfort Trends',
      category: 'womens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/1.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/2.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/3.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Black%20&%20Brown%20Slipper/4.png',
      ],
    },
    {
      id: 94,
      title: 'Calvin Klein Heel Shoes',
      description:
        'Calvin Klein Heel Shoes are elegant and sophisticated, designed for formal occasions. With a classic design and high-quality materials, they complement your stylish ensemble.',
      price: 79.99,
      discountPercentage: 11.39,
      rating: 4.06,
      stock: 99,
      brand: 'Calvin Klein',
      category: 'womens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/1.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/2.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/3.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Calvin%20Klein%20Heel%20Shoes/4.png',
      ],
    },
    {
      id: 95,
      title: 'Golden Shoes Woman',
      description:
        'The Golden Shoes for Women are a glamorous choice for special occasions. Featuring a golden hue and stylish design, they add a touch of luxury to your outfit.',
      price: 49.99,
      discountPercentage: 14.93,
      rating: 4.82,
      stock: 99,
      brand: 'Fashion Diva',
      category: 'womens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/1.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/2.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/3.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Golden%20Shoes%20Woman/4.png',
      ],
    },
    {
      id: 96,
      title: 'Pampi Shoes',
      description:
        'Pampi Shoes offer a blend of comfort and style for everyday use. With a versatile design, they are suitable for various casual occasions, providing a trendy and relaxed look.',
      price: 29.99,
      discountPercentage: 0.3,
      rating: 3.01,
      stock: 36,
      brand: 'Pampi',
      category: 'womens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/1.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/2.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/3.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Pampi%20Shoes/4.png',
      ],
    },
    {
      id: 97,
      title: 'Red Shoes',
      description:
        'The Red Shoes make a bold statement with their vibrant red color. Whether for a party or a casual outing, these shoes add a pop of color and style to your wardrobe.',
      price: 34.99,
      discountPercentage: 0.01,
      rating: 4.23,
      stock: 53,
      brand: 'Fashion Express',
      category: 'womens-shoes',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/1.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/2.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/3.png',
        'https://cdn.dummyjson.com/products/images/womens-shoes/Red%20Shoes/4.png',
      ],
    },
    {
      id: 98,
      title: 'IWC Ingenieur Automatic Steel',
      description:
        'The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.',
      price: 4999.99,
      discountPercentage: 5.76,
      rating: 2.58,
      stock: 85,
      brand: 'IWC',
      category: 'womens-watches',
      thumbnail:
        'https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/1.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/2.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/3.png',
      ],
    },
    {
      id: 99,
      title: 'Rolex Cellini Moonphase',
      description:
        'The Rolex Cellini Moonphase watch is a masterpiece of horology. Featuring a moon phase complication, it showcases the craftsmanship and elegance that Rolex is renowned for.',
      price: 15999.99,
      discountPercentage: 18.76,
      rating: 3.41,
      stock: 66,
      brand: 'Rolex',
      category: 'womens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/1.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/2.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/3.png',
      ],
    },
    {
      id: 100,
      title: 'Rolex Datejust Women',
      description:
        "The Rolex Datejust Women's watch is an iconic timepiece designed for women. With a timeless design and a date complication, it offers both elegance and functionality.",
      price: 10999.99,
      discountPercentage: 17.72,
      rating: 3.53,
      stock: 31,
      brand: 'Rolex',
      category: 'womens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/1.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/2.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/3.png',
      ],
    },
    {
      id: 101,
      title: 'Watch Gold for Women',
      description:
        "The Gold Women's Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.",
      price: 799.99,
      discountPercentage: 6.37,
      rating: 3.03,
      stock: 94,
      brand: 'Fashion Gold',
      category: 'womens-watches',
      thumbnail: 'https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/thumbnail.png',
      images: [
        'https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/1.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/2.png',
        'https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/3.png',
      ],
    },
    {
      id: 102,
      title: "Women's Wrist Watch",
      description:
        "The Women's Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.",
      price: 129.99,
      discountPercentage: 17.34,
      rating: 2.93,
      stock: 55,
      brand: 'Fashion Co.',
      category: 'womens-watches',
      thumbnail: "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/thumbnail.png",
      images: [
        "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/1.png",
        "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/2.png",
        "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/3.png",
      ],
    },
  ],
};

export default goodsData;
