import './style.scss';
import './script.ts';
import './modal.ts';
import './goods.ts';
import './helpers/get-values';
import './helpers/filters';
import './helpers/sorting';
import './pages/product-details/details.scss'
import './pages/product-details/details'